# PostgreSQL configuration for Rails 8+ with Solid stack
#
# Requires: gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: contextqmd_registry_development
  cache:
    <<: *primary_development
    database: contextqmd_registry_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: contextqmd_registry_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: contextqmd_registry_development_cable
    migrations_paths: db/cable_migrate

test:
  primary: &primary_test
    <<: *default
    database: contextqmd_registry_test
    host: <%= ENV.fetch("POSTGRES_HOST", nil) %>
    username: <%= ENV.fetch("POSTGRES_USER", nil) %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", nil) %>
  cache:
    <<: *primary_test
    database: contextqmd_registry_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_test
    database: contextqmd_registry_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_test
    database: contextqmd_registry_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: contextqmd_registry_production
    username: contextqmd_registry
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: contextqmd_registry_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: contextqmd_registry_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: contextqmd_registry_production_cable
    migrations_paths: db/cable_migrate
