module Analytics
  module SourceCatalog
    SOURCE_MAP = {
      "Gmail" => /(^|\.)mail\.google\.com$|(^|\.)gmail\./i,
      "Outlook.com" => /(^|\.)outlook\.|(^|\.)live\.|(^|\.)office\.com/i,
      "Yahoo! Mail" => /(^|\.)mail\.yahoo\./i,
      "Proton Mail" => /(^|\.)mail\.proton\.me$/i,
      "iCloud Mail" => /(^|\.)mail\.icloud\.com$/i,
      "Google" => /(^|\.)google\./i,
      "Bing" => /(^|\.)bing\./i,
      "DuckDuckGo" => /duckduckgo/i,
      "Yahoo!" => /(^|\.)yahoo\./i,
      "Baidu" => /(^|\.)baidu\./i,
      "Yandex" => /(^|\.)yandex\./i,
      "Ecosia" => /(^|\.)ecosia\./i,
      "Qwant" => /(^|\.)qwant\./i,
      "Brave" => /(^|\.)search\.brave\./i,
      "AOL" => /(^|\.)aol\./i,
      "Ask" => /(^|\.)ask\./i,
      "Naver" => /(^|\.)naver\./i,
      "Seznam" => /(^|\.)seznam\./i,
      "Sogou" => /(^|\.)sogou\./i,
      "Startpage" => /(^|\.)startpage\./i,
      "Perplexity" => /(^|\.)perplexity\./i,
      "ChatGPT" => /(^|\.)chatgpt\./i,
      "Facebook" => /(^|\.)facebook\./i,
      "Instagram" => /(^|\.)instagram\./i,
      "Twitter" => /(^|\.)twitter\.|(^|\.)x\.com/i,
      "LinkedIn" => /(^|\.)linkedin\./i,
      "Pinterest" => /(^|\.)pinterest\./i,
      "Reddit" => /(^|\.)reddit\./i,
      "YouTube" => /(^|\.)youtube\.|(^|\.)youtu\.be/i,
      "TikTok" => /(^|\.)tiktok\./i,
      "WhatsApp" => /(^|\.)whatsapp\./i,
      "Telegram" => /(^|\.)telegram\./i,
      "Snapchat" => /(^|\.)snapchat\./i,
      "Threads" => /(^|\.)threads\.net/i,
      "Discord" => /(^|\.)discord\./i,
      "Quora" => /(^|\.)quora\./i,
      "VK" => /(^|\.)vk\.com/i,
      "Weibo" => /(^|\.)weibo\./i,
      "GitHub" => /(^|\.)github\./i,
      "StackOverflow" => /(^|\.)stackoverflow\./i,
      "Stack Overflow" => /(^|\.)stackoverflow\./i,
      "Hacker News" => /(^|\.)news\.ycombinator\.com$/i
    }.freeze
  end
end
